"""init

Revision ID: 1655cddbeac0
Revises: 
Create Date: 2026-05-22 11:24:59.755546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1655cddbeac0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # employees 테이블에 없는 고아 레코드 삭제
    op.execute(
        "DELETE FROM attendance_records "
        "WHERE employee_id NOT IN (SELECT id FROM employees)"
    )
    op.alter_column('attendance_records', 'action_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('CHECK_IN', 'OUTING', 'RETURN', 'LUNCH', 'EARLY_LEAVE', 'CHECK_OUT', name='actiontype'),
               existing_nullable=False)
    op.create_foreign_key(None, 'attendance_records', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.alter_column('attendance_records', 'action_type',
               existing_type=sa.Enum('CHECK_IN', 'OUTING', 'RETURN', 'LUNCH', 'EARLY_LEAVE', 'CHECK_OUT', name='actiontype'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
