# attendance_id_int_to_uuid
#
# Revision ID: 4aa952dff56b
# Revises: 1655cddbeac0
# Create Date: 2026-05-22 14:20:58.053654

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4aa952dff56b'
down_revision: Union[str, Sequence[str], None] = '1655cddbeac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Upgrade schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_logs', 'attendance_id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('attendance_records', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('attendance_logs', 'attendance_id',
               existing_type=sa.Uuid(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
