"""add_index_and_fk_cascade

Revision ID: 706f8af0442b
Revises: 842e73693429
Create Date: 2026-06-01 16:32:13.733655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706f8af0442b'
down_revision: Union[str, Sequence[str], None] = '842e73693429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendance_logs', 'attendance_records', ['attendance_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_attendance_employee_recorded', 'attendance_records', ['employee_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_employee_recorded', table_name='attendance_records')
    op.drop_constraint(None, 'attendance_logs', type_='foreignkey')
    # ### end Alembic commands ###
