"""add_action_type_to_attendance_logs

Revision ID: 842e73693429
Revises: a1b2c3d4e5f6
Create Date: 2026-06-01 11:13:25.600073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842e73693429'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_logs', sa.Column('before_action_type', sa.Enum('ENTER', 'EXIT', name='actiontype'), nullable=False))
    op.add_column('attendance_logs', sa.Column('after_action_type', sa.Enum('ENTER', 'EXIT', name='actiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_logs', 'after_action_type')
    op.drop_column('attendance_logs', 'before_action_type')
    # ### end Alembic commands ###
